### ISSUE TITLE
Black screen on Windows

### ISSUE THREAD

**Issue by petrbulusek** [moshe-rabaev/LiquidFun-Cocos2dx#1]
Hi, should it work on Windows? I see only black screen and no particles.

**Comment by codinghaven** [comment]
Are you using the sample project?

**Comment by petrbulusek** [comment]
Yes

**Comment by codinghaven** [comment]
I have only tested it on android in fact I'm assuming it only works on android.
I will expand it to work on all the platforms that cocos2d-x supports in the near future.

I don't have a windows machine to test on but will have one in like 2 weeks.

Did you test on android?

It should look like stars are twinkling over a dark screen.
![Screen Shot 2019-04-15 at 5 01 50 PM](https://user-images.githubusercontent.com/12215501/56164911-b30e2c00-5f9f-11e9-9bcb-6755dab04786.png)

**Comment by codinghaven** [comment]
IOS now works with sample project and with `cocos new...`
I will add changes to the project in regards to windows asap, whenever I get that windows machine :)
I will let you know.

**Comment by petrbulusek** [comment]
Hi, I saw you basically took the EyeCandy sample. I am now testing the sample from cocos2d repository and it works, maybe I was doing something wrong, but thanks.
